### ISSUE TITLE
child_process.fork一个es语法的ts文件报错

### ISSUE THREAD

**Issue by swordsman-coder** [xeajs/electron#2]
如何支持fork一个文件的时候支持es语法呢
![image](https://user-images.githubusercontent.com/16441180/125891135-0924f8a8-c74e-49b0-a00c-627d645bba71.png)

**Comment by yejiang1015** [comment]
@swordsman-coder  fork 需要传入的是一个 CommonJS 模块的js文件path。你引用的是一个 ts 的 esmodule 模块；模块之间不兼容。你可以考虑吧你需要引用的模块单独打包为js文件并且是 CommonJS模块。就可以正常使用。或者换一个方案实现功能

**Comment by swordsman-coder** [comment]
已经改为单独打包 感谢
